name: abil-env
channels:
  - defaults
  - conda-forge
dependencies:
  - netcdf4
  - dask
  - numpy
  - pandas
  - pyyaml
  - xarray
  - xgboost==1.7.6
  - ipykernel
  - scikit-learn==1.3.0
  - scipy
  - mapie==0.8.6
  - scikit-bio